### PR TITLE
[14.0][IMP] connector_search_engine: force sequentiality for batch export per index

### PR DESCRIPTION
**Pull request by hparfr**
Force all the batchs for a given index to be exported one after the other, inside  a (queue_job) chain.

Then if some reason a job fail to export, like a unreachable server then it pause all the consecutives jobs.

It makes the errors easier to troubleshoot (less noise) and probably help to not saturate the se server with lot of // update requests on the same index.

### CODE REVIEW

**Comment by hparfr** [comment]
@sebastienbeau

**Review by nayatec — COMMENTED** [review]
Yes, this one is usefull and works well in prod already

**Comment by hparfr** [comment]
@sebastienbeau @lmignon any chance to review this one ?

**Review by lmignon — APPROVED** [review]

**Comment by lmignon** [comment]
@hparfr Can you check the tests PLZ

**Review by nayatec — APPROVED** [review]

**Pull request closed without merging**
