### PR TITLE
[13.0] [IMP] connector_search_engine: avoid write on bindings when force export

### PR DESCRIPTION
**Pull request by ThomasBinsfeld**
More performant and avoid concurrency issues.

### CODE REVIEW

**Review by rousseldenis — APPROVED** [review]
Code review. LGTM

@sebastienbeau @Laurent-Corron

**Review by lmignon — APPROVED** [review]
Good catch! (Code review)

**Review by sebastienbeau — APPROVED** [review]
LGTM code review

**Pull request merged**
