### PR TITLE
connector_elasticsearch: Requests fail on >=7.14.0

### PR DESCRIPTION
**Pull request by rousseldenis**

### CODE REVIEW

**Comment by sbidoul** [comment]
Can you provide the error that makes this change necessary ?

**Comment by rousseldenis** [comment]
> Can you provide the error that makes this change necessary ?

See https://github.com/shopinvader/odoo-shopinvader/runs/3241083055

Same as in 14 (and I think in every versions)

**Comment by sebastienbeau** [comment]
Can you try to re-record the test? I think the issue it that the lib do not do the same request (additionnal HEAD request) and so the mock cassette are broken.
On V14 I have re-recorded the test https://github.com/shopinvader/odoo-shopinvader/pull/1016

**Comment by sebastienbeau** [comment]
In any case It's ok for me if we prefers to stay on version <=7.13.4 for the 10 version

**Pull request closed without merging**
