### PR TITLE
[13.0][MIG] connector algolia

### PR DESCRIPTION
**Pull request by Laurent-Corron**
requires:
- [x] includes connector_search_engine #33 
- [x]  component [PR](https://github.com/OCA/connector/pull/355)

### CODE REVIEW

**Review by lmignon — APPROVED** [review]
LGTM (Code review)

**Comment by simahawk** [comment]
LG. Can you:
1. review #38 
2. we merge it 
3. cherry-pick it here?

**Comment by lmignon** [comment]
@simahawk merging #38 You're the only one using this addon therefore we can't expect more reviewers :smirk:

**Comment by rousseldenis** [comment]
This is rebased.

**Review by rousseldenis — APPROVED** [review]
Code review. Easy one

**Pull request merged**
