### PR TITLE
[10.0] Refactor test by using odoo-test-lib

### PR DESCRIPTION
**Pull request by sebastienbeau**
As I have some issue in base_url I am playing on a new implementation of testing with fake model.
if you want to comment please comment here : https://github.com/shopinvader/odoo-shopinvader/pull/607

### CODE REVIEW

**Comment by sebastienbeau** [comment]
@lmignon @sbidoul any idea why the build on wheel fail?

**Comment by sbidoul** [comment]
@sebastienbeau I suspect it is due to [this hack](https://github.com/OCA/maintainer-quality-tools/blob/ce728c28d14afc983c0b58081cd92243c0f9085e/travis/travis_install_nightly#L104). I don't know why it is there and what would happen if we remove it though.

**Comment by sbidoul** [comment]
You can add `MQT_DEP=PIP` in the global env section of .travis.yml to enable a modern [installation method](https://github.com/OCA/maintainer-quality-tools/blob/ce728c28d14afc983c0b58081cd92243c0f9085e/travis/travis_install_nightly#L119-L134) that does not depend on oca_dependencies.txt nor requirements.txt, and is free of historical cruft. This may help.

**Comment by sebastienbeau** [comment]
Last failling test seem to be linked to a change in elastic lib (POST instead of a GET)

With the old lib version
Sélection_039


With the new one
Sélection_038

I am going to re-record the test

**Comment by sebastienbeau** [comment]
@sbidoul @gurneyalex It's seem that we have an issue with the version of cachetools on runbot any idea?

**Comment by sebastienbeau** [comment]
For now odoo-test-lib is here : https://github.com/akretion/odoo-test-helper

**Comment by sebastienbeau** [comment]
I am closing this PR as keep the focus on last version

**Pull request closed without merging**
