### PR TITLE
[14.0] c_elasticsearch: fix settings export

### PR DESCRIPTION
**Pull request by simahawk**
Export settings is currently broken.

The role of _get_es_client should be only to get the client
and not to initialize the index if missing.

The role of settings export is to exactly this:
make sure the index is set up properly.

### CODE REVIEW

**Review by jcoux — APPROVED** [review]

**Comment by simahawk** [comment]
@lmignon can I have your feedback on this?

**Comment by sebastienbeau** [comment]
@hparfr

**Review by hparfr — APPROVED** [review]
LGTM

**Pull request merged**
