### PR TITLE
[16.0][FIX] search_engine_image_thumbnail: field type binary

### PR DESCRIPTION
**Pull request by qgroulard**
see https://github.com/OCA/search-engine/issues/183

* [x]  includes [[16.0] search_engine_image_thumbnail: New config param #176](https://github.com/OCA/search-engine/pull/176)

### CODE REVIEW

**Comment by qgroulard** [comment]
Ping @lmignon, it would be nice to merge all those fixes.

**Comment by lmignon** [comment]
> Ping @lmignon, it would be nice to merge all those fixes.

We've to fix the bot. The generation of the history file doesn't work with md files. (I hope to have some time in the next week to fix this issue)

**Review by lmignon — APPROVED** [review]

**Pull request merged**
