### PR TITLE
[FIX] search_engine_image_thumbnail: fix the domain type for image fields filter

### PR DESCRIPTION
**Pull request by kobros-tech**
The datatype of the domain in the computed method was not correct.
It is reviewed with ACSONE.

It is an extension of a closed pull request:
[https://github.com/OCA/search-engine/pull/198](https://github.com/OCA/search-engine/pull/198)

@lmignon

### CODE REVIEW

**Comment by lmignon** [comment]
@kobros-tech Can you fix the tests and pre-commit? Thank you for your debugging and correction work.

**Comment by kobros-tech** [comment]
@lmignon 
All tests succeeded after pre-commit and setting up the test correctly.

**Review by lmignon — APPROVED** [review]

**Comment by kobros-tech** [comment]
@OCA-git-bot 
@simahawk 
@sebastienbeau

**Pull request merged**
