### PR TITLE
[FIX] connector_search_engine: Invalidate se_binding_ids on binding CRUD

### PR DESCRIPTION
**Pull request by lmignon**
When bindings are created / updated / unlinked, we must invalidate the 'se_binding_ids' field of related records. In the case of an update, the invalidation is only done if the reference to the record changes

### CODE REVIEW

**Review by qgroulard — APPROVED** [review]
Code review

**Comment by lmignon** [comment]
ping @qgroulard @rousseldenis

**Review by rousseldenis — APPROVED** [review]
Code review

**Pull request merged**
