### PR TITLE
[14.0] Misc migration to v14

### PR DESCRIPTION
**Pull request by sebastienbeau**
Do not merge yet
- [ ] migrate to new queu job in V13 and rebase this work #68
- [ ] update algolia client in V13 and rebase this work

### CODE REVIEW

**Comment by PierrickBrun** [comment]
I can't edit the original post so here is the actual state of the PR:

 - [x] migrate to new queu job in V13 and rebase this work #68 
 - [ ] update algolia client in V13 and rebase this work #73

**Comment by simahawk** [comment]
@sebastienbeau @PierrickBrun sorry but this PR looks messy both in terms of contents and commits. Can we split things? Do you mind if I do it?

**Comment by simahawk** [comment]
I'd port queue job and base_jsonify changes as they are in separated PRs even if the build won't run.

**Comment by simahawk** [comment]
step 1 https://github.com/OCA/search-engine/pull/82

**Comment by simahawk** [comment]
step 2 https://github.com/OCA/search-engine/pull/83

**Comment by simahawk** [comment]
step 3 https://github.com/OCA/search-engine/pull/84

**Comment by simahawk** [comment]
step 4 https://github.com/OCA/search-engine/pull/85

**Comment by simahawk** [comment]
pls refer to #84.

For algolia I'll open another PR later after testing #73 on real project.

**Comment by simahawk** [comment]
step 5 https://github.com/OCA/search-engine/pull/86

**Comment by sebastienbeau** [comment]
@simahawk perfect ! Thanks a lot

**Pull request closed without merging**
