### PR TITLE
[13.0][IMP] connector_elasticsearch: Add API key support to Elasticsearch connector

### PR DESCRIPTION
**Pull request by dcoleman-lulzbot**
Allows the usage of an Elasticsearch API key, enabling the module to work with X-Pack security.

### CODE REVIEW

**Comment by JordiBForgeFlow** [comment]
@HviorForgeFlow

**Review by lmignon — COMMENTED** [review]
LGTM but pre-commit is failing

**Comment by lmignon** [comment]
For the record, you can also use [opendisto](https://opendistro.github.io/for-elasticsearch-docs/docs/security/) to secure your ES indexes. The security extension is easy to install and configure and is OS.

**Review by lmignon — APPROVED** [review]
Thank you for the change @dcoleman-lulzbot . Nitpicking: For readability I would have preferred the initialization of `api_key` params to be done outside of the call to the constructor...
```python
api_key = None
if backend.api_key_id and backend.api_key:
    api_key=(backend.api_key_id, backend.api_key)
es= elasticsearch.Elasticsearch(
    [backend.es_server_host], connection_class=self._es_connection_class, api_key=api_key)
```

**Review by PierrickBrun — APPROVED** [review]

**Review by lmignon — APPROVED** [review]

**Pull request merged**
