### PR TITLE
[13.0] Improve validation of index record data

### PR DESCRIPTION
**Pull request by simahawk**
* record main validation delegated to backend (it really depends on the kind of search engine)
* can be overridden at adapter level (here it still breaks to make sure you don't send crap to the SE)
* can be overridden at binding level to validate values specific to your own model (here it does not break)
* if the validation does not pass on index data re-computation, sync state is set "To be checked".
This way, failing records won't be considered for export (avoid failing exports) and will be set aside for checking them.

Note: travis tests here might fail but they were fixed in https://github.com/OCA/search-engine/pull/50 which is still waiting for validation on odoo-test-helper version upgrade.

### CODE REVIEW

**Comment by simahawk** [comment]
@lmignon could you pass by here as well? :pray:

**Review by lmignon — APPROVED** [review]
Thank you @simahawk. Once again the modularity is pushed a step forward. LGTM (Code review)

**Pull request merged**
