### PR TITLE
[13.0][MIG] connector_search_engine

### PR DESCRIPTION
**Pull request by Laurent-Corron**
requires:
- [x] base_jsonify [PR](https://github.com/OCA/server-tools/pull/1704)
- [x] connector [PR](https://github.com/OCA/connector/pull/357)

### CODE REVIEW

**Comment by lmignon** [comment]
cc @simahawk @rousseldenis @Cedric-Pigeon

**Review by Cedric-Pigeon — APPROVED** [review]
LGTM

**Review by simahawk — APPROVED** [review]
LG

**Pull request merged**
