### PR TITLE
[15.0] [MIG] connector_search_engine

### PR DESCRIPTION
**Pull request by JasminSForgeFlow**
Standard Migration

@ForgeFlow

Depends on:

- https://github.com/OCA/server-tools/pull/2278

### CODE REVIEW

**Comment by HviorForgeFlow** [comment]
@JasminSForgeFlow can you include https://github.com/OCA/search-engine/commit/c3e523038fb703ab6145b374842eaae9b9dfa581 thanks!

**Comment by JasminSForgeFlow** [comment]
> @JasminSForgeFlow can you include [c3e5230](https://github.com/OCA/search-engine/commit/c3e523038fb703ab6145b374842eaae9b9dfa581) thanks!

Done, Thanks

**Review by MiquelRForgeFlow — APPROVED** [review]

**Review by LoisRForgeFlow — APPROVED** [review]
Code review LGTM

**Review by HviorForgeFlow — APPROVED** [review]

**Pull request merged**
