### PR TITLE
[16.0] search_engine_image_thumbnail: New config param

### PR DESCRIPTION
**Pull request by lmignon**
* [ ] includes #174 

Add new config parameter on the search engine backend to allow the user to specify if the serialization of a record should fail if thumbnails are requested but no thumbnail sizes are defined for the model and field for which it' requested. Defaults to False (i.e. don't fail).

### CODE REVIEW

**Comment by lmignon** [comment]
@qgroulard @sbejaoui @sebastienbeau

**Review by qgroulard — APPROVED** [review]

**Pull request merged**
