### PR TITLE
[12.0][FIX] connector_search_engine: Three fixes that causes WARNING

### PR DESCRIPTION
**Pull request by rousseldenis**

### CODE REVIEW

**Comment by rousseldenis** [comment]
@lmignon @sebastienbeau @simahawk

**Comment by simahawk** [comment]
seems black is not happy

**Comment by rousseldenis** [comment]
Done!

**Review by lmignon — APPROVED** [review]

**Review by simahawk — APPROVED** [review]
LG

**Review by sebastienbeau — APPROVED** [review]

**Pull request closed without merging**
